### PR TITLE
now you can edit existing parameters names and new parameters are included in the updated url even if the "onblur" event fails

### PR DESCRIPTION
**Pull request by JaderDias**

### CODE REVIEW

**Comment by inuyasha82** [comment]
Hi @JaderDias, i checked this pull request, and it pointed me out to several problems regarding the new parameter (after changing from div to table), and i discovered that the code on the onblur function isn't working anymore, but the fix is more straitghforward (you can check the pull request #42). Basically it was still based on the div structure, and all relationship (parent, child, siblings) are not working for the table. The update in my pull request try to fix all these issues. 

Thank you for your effort, i will  close this request without merging, just because i found the issues in the actual code, and fixed them.

**Comment by inuyasha82** [comment]
You can check all the updates now on the dev branch!

**Comment by JaderDias** [comment]
does your fix allow for the same parameter to be added twice? some web apps require this
does your fix allow to rename existing parameters?
both features are included in my pull request

**Comment by inuyasha82** [comment]
Ok for the firs question the answer is yes, is a sort of buil-in (just tried). 
The second is no. But probably since your pull request was based on a faulty version of the code, now it should be easier to add these feature.

**Comment by inuyasha82** [comment]
Anyway i suggest you my idea, the parameter name field should be disabled when the user open the extension, and it will be enabled and made editable when the user click on it.

**Comment by JaderDias** [comment]
I don't see why would you do that, if it's editable it's editable, no point in showing it as disabled

**Comment by inuyasha82** [comment]
Just for keep the same look and feel, or at least the idea is to find a way to show parameter_name and parameter_value in two different way (like now, or in the older version). I'm open to suggestion. (i like the actual look and feel, where you can clearly recognize parameters)

**Comment by inuyasha82** [comment]
Anyway, what you can do (clearly if you want) is to prepare another pull request with the edit feature for parameter_name, i like the idea, just what i ask is to find a way to keep parameter name and parameter field different. 
Here some ideas:

1. Add an edit names link that enable all the text field in parameter_name?
2. Change the style of the input box if possible. (Here some ideas: http://callmenick.com/_development/input-text-styles/) 
3. Maybe just changing the background and font colors?

I'll open a task for the 1.3 release, if you want you can assign it to yourself.

**Pull request closed without merging**
